version: "3.8"
services: 
    match_stats_bot:
        container_name: "dota_bot"
        build:
            context: .
            dockerfile: Dockerfile.dev
        env_file: .env
        volumes: 
            - ./app:/usr/src/app/app
        networks:
            - skillreview
        ports: 
            - 8081:8081
        entrypoint: ['python', '-m', 'app']

networks:
    skillreview:
        name: backend_skillreview