version: "3.8"
services: 
    match_stats_bot:
        container_name: "dota_bot"
        build:
            context: .
            dockerfile: Dockerfile.dev
        env_file: .env
        volumes: 
            - ./app:/usr/src/app/app
        networks:
            - ulnet_testing
        ports: 
            - 8080:8080
        entrypoint: ['python', '-m', 'app']

networks:
    ulnet_testing:
        name: ul_testing_network