version: "3.8"
services: 
    match_stats_bot:
        container_name: "dota_bot"
        build:
            context: .
            dockerfile: Dockerfile.dev
        env_file: app/.env
        ports: 
            - 8080:8080
        entrypoint: ['python', 'main.py']