{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart-match-stats.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "chart-match-stats.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
{{ include "chart-match-stats.selector" . | indent 4 }}
{{- end }}
